# Generated by Django 5.1.3 on 2024-11-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=150)),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.companies')),
                ('servic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.services')),
                ('technic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tecnicos.technicians')),
            ],
            options={
                'ordering': ['date_start'],
            },
        ),
    ]
