# Generated by Django 5.1.3 on 2025-01-03 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('is_working', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.companies')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.services')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnicos.technicians')),
            ],
            options={
                'ordering': ['date_start'],
                'unique_together': {('technician', 'date_start')},
            },
        ),
    ]
