# Generated by Django 5.1.3 on 2024-11-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('corporate_reason', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('cell', models.CharField(max_length=11)),
            ],
            options={
                'ordering': ['corporate_reason'],
            },
        ),
    ]
