# Generated by Django 5.1.3 on 2025-01-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='cell',
            field=models.CharField(max_length=15, verbose_name='Cel'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='Tel'),
        ),
    ]
